# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$time$cmd_duration"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[character]
success_symbol = "[âœ](bold #98c379)" #green
error_symbol = "[âœ](bold #e06c75)" #red

[cmd_duration]
format = " took [ï€— $duration]($style)"
style = "bold" #white

[time]
time_format = "%R" # Hour:Minute Format
format = '[ â™¥ $time ]($style)'

[directory]
read_only = " ï ½"
style = "bold #c678dd" #purple

[git_branch]
symbol = "ï˜"
style = "bold #e31b1b"
format = 'on[ $symbol $branch ]($style)'

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](style:'green') "
modified = "[${count}+](style:'yellow') "
deleted =  "[${count}-](style:'red') "
conflicted =  "[${count}~](style:'red') "
ahead = "â‡¡${count} "
behind = "â‡£${count} "
untracked = "[${count}?](style:'blue') "
staged = "[${count}+](style:'green') "

[java]
symbol = "î‰– "
style = "bold #61afef" #blue

[nix_shell]
symbol = "ïŒ“ "
style = "bold #61afef" #blue
impure_msg = " [impure](bold #e06c75)"
pure_msg = " [pure](bold)"

[nodejs]
symbol = "îœ˜"
format = 'via[ $symbol ($version) ]($style)'
style = "bold #98c379" #green
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[rust]
symbol = "î¨"
style = "bold #86BBD8"
format = '[ $symbol ($version) ]($style)'

[package]
style = "bold #e06c75" #red

[python]
symbol = "ï Ÿ "
format = 'via[ $symbol ($version) ]($style)'
style = "bold #e5c07b" #yellow

[docker_context]
symbol = "ïŒˆ "
format = '[ $symbol $context ]($style) $path'

[golang]
symbol = "î˜§ "
format = 'via[ $symbol ($version) ]($style)'

[ruby]
symbol = "îˆ¾ "
style = "bold #e06c75" #red

[aws]
disabled = true
symbol = "îŒ½  "

[lua]
disabled = true

